import * as path from 'path';
import { BaseGenerator } from '../../../../core/generators/base_generator';
import { IFileSystem } from '../../../../core/interfaces/file_system';
import { ServerDataConfig } from '../../parsers/server_data_parser';

export class TerraformMainGenerator extends BaseGenerator<ServerDataConfig> {
  constructor(fileSystem: IFileSystem) {
    super(fileSystem);
  }

  protected getPath(basePath: string, _name?: string, _data?: ServerDataConfig): string {
    const projectName = path.basename(basePath);
    return path.join(basePath, `${projectName}_server`, 'terraform', 'main.tf');
  }

  protected getContent(data?: ServerDataConfig): string {
    if (!data) {
      throw new Error('ServerDataConfig not provided');
    }

    const appName = data.project.name;
    const organization = data.deployment?.organization || 'devabacus';
    const dbName = data.database.name;
    const dbUser = data.database.user;
    const serverIp = data.server.ip;
    const domain = data.server.domain;
    const apiSubdomain = data.server.subdomain.api;
    const webSubdomain = data.server.subdomain.web;
    const insightsSubdomain = data.server.subdomain.insights;

    return `# Terraform configuration for ${appName}
# Generated by code-generator extension
#
# Usage:
#   cd ${appName}_server/terraform
#   .\\apply.ps1
#
# This will:
#   1. Create DNS A-records for subdomains (api, web, insights)
#   2. Create PostgreSQL database and user in Timeweb
#   3. Configure all GitHub Secrets

terraform {
  required_version = ">= 1.0.0"
  
  required_providers {
    twc = {
      source  = "timeweb-cloud/timeweb-cloud"
      version = "~> 1.0"
    }
    github = {
      source  = "integrations/github"
      version = "~> 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
  }
}

# -- Read secrets from files --

locals {
  timeweb_token   = trimspace(file(var.timeweb_token_path))
  github_token    = trimspace(file(var.github_token_path))
  redis_password  = trimspace(file(var.redis_password_path))
  kube_config     = file(var.kube_config_path)  # Raw YAML, not base64
  registry_domain = trimspace(file(var.registry_domain_path))
  registry_user   = trimspace(file(var.registry_user_path))
}

# -- Providers --

provider "twc" {
  token = local.timeweb_token
}

provider "github" {
  token = local.github_token
  owner = "${organization}"
}

# -- Auto-generated secrets --

resource "random_password" "db_password" {
  length           = 24
  special          = true
  min_lower        = 4
  min_upper        = 4
  min_numeric      = 4
  min_special      = 2
  override_special = "!@#"  # Timeweb-compatible
}

resource "random_password" "service_secret" {
  length  = 48
  special = true
}

# -- Timeweb DNS Zone and Subdomains --

data "twc_dns_zone" "main" {
  name = "${domain}"
}

resource "twc_dns_rr" "api" {
  zone_id = data.twc_dns_zone.main.id
  name    = "${apiSubdomain}"
  type    = "A"
  value   = "${serverIp}"
}

resource "twc_dns_rr" "web" {
  zone_id = data.twc_dns_zone.main.id
  name    = "${webSubdomain}"
  type    = "A"
  value   = "${serverIp}"
}

resource "twc_dns_rr" "insights" {
  zone_id = data.twc_dns_zone.main.id
  name    = "${insightsSubdomain}"
  type    = "A"
  value   = "${serverIp}"
}

# -- Timeweb PostgreSQL Database and User --

# Create database instance in existing cluster
resource "twc_database_instance" "main" {
  cluster_id = var.postgres_cluster_id
  name       = "${dbName}"
}

# Create database user with access to the database
# NOTE: Timeweb API does not provide CONNECT privilege.
# After running apply.ps1, go to Timeweb Console -> Databases -> Users -> ${dbUser}
# Select the database and enable "Выбрать все привилегии" (Select all privileges)
resource "twc_database_user" "main" {
  cluster_id = var.postgres_cluster_id
  login      = "${dbUser}"
  password   = random_password.db_password.result
  privileges = ["SELECT", "INSERT", "UPDATE", "DELETE"]
}

# -- GitHub Secrets --

resource "github_actions_secret" "db_password" {
  repository      = "${appName}"
  secret_name     = "DB_PASSWORD"
  plaintext_value = random_password.db_password.result
}

resource "github_actions_secret" "redis_password" {
  repository      = "${appName}"
  secret_name     = "REDIS_PASSWORD"
  plaintext_value = local.redis_password
}

resource "github_actions_secret" "service_secret" {
  repository      = "${appName}"
  secret_name     = "SERVICE_SECRET"
  plaintext_value = random_password.service_secret.result
}

resource "github_actions_secret" "registry_user" {
  repository      = "${appName}"
  secret_name     = "REGISTRY_USER"
  plaintext_value = local.registry_user
}

resource "github_actions_secret" "registry_password" {
  repository      = "${appName}"
  secret_name     = "REGISTRY_PASSWORD"
  plaintext_value = local.timeweb_token
}

resource "github_actions_secret" "registry_email" {
  repository      = "${appName}"
  secret_name     = "REGISTRY_EMAIL"
  plaintext_value = var.timeweb_email
}

resource "github_actions_secret" "registry_domain" {
  repository      = "${appName}"
  secret_name     = "REGISTRY_DOMAIN"
  plaintext_value = local.registry_domain
}

resource "github_actions_secret" "kube_config" {
  repository      = "${appName}"
  secret_name     = "KUBE_CONFIG"
  plaintext_value = local.kube_config  # Raw YAML, not base64
}

# -- Outputs --

output "db_name" {
  value = twc_database_instance.main.name
}

output "db_user" {
  value = twc_database_user.main.login
}

output "db_password" {
  value       = random_password.db_password.result
  sensitive   = true
}

output "service_secret" {
  value     = random_password.service_secret.result
  sensitive = true
}

output "dns_subdomains" {
  value = <<-EOT
    
    DNS A-records created:
      ${apiSubdomain}.${domain} -> ${serverIp}
      ${webSubdomain}.${domain} -> ${serverIp}
      ${insightsSubdomain}.${domain} -> ${serverIp}
    
  EOT
}

output "next_steps" {
  value = <<-EOT
    
    ✅ Infrastructure configured!
    
    Created in Timeweb:
      DNS: ${apiSubdomain}.${domain}, ${webSubdomain}.${domain}, ${insightsSubdomain}.${domain}
      Database: ${dbName}
      User: ${dbUser}
      
    Configured in GitHub Secrets:
      DB_PASSWORD, REDIS_PASSWORD, SERVICE_SECRET
      REGISTRY_USER, REGISTRY_PASSWORD, REGISTRY_EMAIL, REGISTRY_DOMAIN
      KUBE_CONFIG
    
    Ready to deploy! Just push to master.
    
  EOT
}
`;
  }
}
