import * as path from 'path';
import { BaseGenerator } from '../../../../core/generators/base_generator';
import { IFileSystem } from '../../../../core/interfaces/file_system';
import { ServerDataConfig } from '../../parsers/server_data_parser';

export class TerraformVariablesGenerator extends BaseGenerator<ServerDataConfig> {
  constructor(fileSystem: IFileSystem) {
    super(fileSystem);
  }

  protected getPath(basePath: string, _name?: string, _data?: ServerDataConfig): string {
    const projectName = path.basename(basePath);
    return path.join(basePath, `${projectName}_server`, 'terraform', 'variables.tf');
  }

  protected getContent(data?: ServerDataConfig): string {
    if (!data) {
      throw new Error('ServerDataConfig not provided');
    }

    return `# Variables for ${data.project.name} Terraform configuration
# Generated by code-generator extension
#
# Secrets are read from files in C:/Users/User/.secrets/

# -- Timeweb PostgreSQL Cluster --
variable "postgres_cluster_id" {
  description = "Existing PostgreSQL cluster ID in Timeweb"
  type        = number
}

# -- File paths to secrets --

variable "timeweb_token_path" {
  description = "Path to file containing Timeweb API token"
  type        = string
  default     = "C:/Users/User/.secrets/timeweb_token"
}

variable "github_token_path" {
  description = "Path to file containing GitHub token"
  type        = string
  default     = "C:/Users/User/.secrets/github_token"
}

variable "redis_password_path" {
  description = "Path to file containing Redis password"
  type        = string
  default     = "C:/Users/User/.secrets/redis_password"
}

variable "kube_config_path" {
  description = "Path to kubeconfig file"
  type        = string
  default     = "C:/Users/User/.kube/config"
}

variable "registry_domain_path" {
  description = "Path to file containing registry domain (e.g., xxx.registry.twcstorage.ru)"
  type        = string
  default     = "C:/Users/User/.secrets/registry_domain"
}

variable "registry_user_path" {
  description = "Path to file containing registry username"
  type        = string
  default     = "C:/Users/User/.secrets/registry_user"
}

# -- Non-secret configuration --

variable "timeweb_email" {
  description = "Timeweb account email (used for registry email)"
  type        = string
  default     = "${data.server.email}"
}
`;
  }
}
