import * as path from 'path';
import { BaseGenerator } from '../../../../core/generators/base_generator';
import { IFileSystem } from '../../../../core/interfaces/file_system';
import { ServerDataConfig } from '../../parsers/server_data_parser';

export class TerraformApplyScriptGenerator extends BaseGenerator<ServerDataConfig> {
    constructor(fileSystem: IFileSystem) {
        super(fileSystem);
    }

    protected getPath(basePath: string, _name?: string, _data?: ServerDataConfig): string {
        const projectName = path.basename(basePath);
        return path.join(basePath, `${projectName}_server`, 'terraform', 'apply.ps1');
    }

    protected getContent(data?: ServerDataConfig): string {
        if (!data) {
            throw new Error('ServerDataConfig not provided');
        }

        return `# Terraform apply script for ${data.project.name}
# Generated by code-generator extension
#
# Usage: .\\apply.ps1

$secretsDir = "C:\\Users\\User\\.secrets"

# Check required secret files
$requiredFiles = @(
    "timeweb_token",
    "github_token", 
    "redis_password",
    "postgres_cluster_id",
    "registry_domain",
    "registry_user"
)
$missingFiles = @()

foreach ($file in $requiredFiles) {
    $filePath = Join-Path $secretsDir $file
    if (-not (Test-Path $filePath)) {
        $missingFiles += $file
    }
}

if ($missingFiles.Count -gt 0) {
    Write-Host "ERROR: Missing secret files:" -ForegroundColor Red
    foreach ($file in $missingFiles) {
        Write-Host "  - \${secretsDir}\\$file" -ForegroundColor Yellow
    }
    Write-Host ""
    Write-Host "Create these files with their values (one value per file)."
    Write-Host ""
    Write-Host "registry_domain: e.g., xxx.registry.twcstorage.ru"
    Write-Host "registry_user: e.g., xxx (same prefix as domain)"
    Write-Host ""
    Write-Host "See README.md for details."
    exit 1
}

# Check kubeconfig
if (-not (Test-Path "C:\\Users\\User\\.kube\\config")) {
    Write-Host "ERROR: kubeconfig not found at C:\\Users\\User\\.kube\\config" -ForegroundColor Red
    exit 1
}

# Read postgres_cluster_id
$clusterId = Get-Content (Join-Path $secretsDir "postgres_cluster_id") -Raw
$clusterId = $clusterId.Trim()

Write-Host "All secret files found!" -ForegroundColor Green
Write-Host "PostgreSQL Cluster ID: $clusterId" -ForegroundColor Cyan
Write-Host ""

Write-Host "Initializing Terraform..." -ForegroundColor Cyan
terraform init

if ($LASTEXITCODE -ne 0) {
    Write-Host "ERROR: terraform init failed" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Applying Terraform configuration..." -ForegroundColor Cyan
Write-Host "This will create:" -ForegroundColor White
Write-Host "  - Database: ${data.database.name}" -ForegroundColor Yellow
Write-Host "  - User: ${data.database.user}" -ForegroundColor Yellow
Write-Host "  - GitHub Secrets" -ForegroundColor Yellow
Write-Host ""

terraform apply -var="postgres_cluster_id=$clusterId" -auto-approve

if ($LASTEXITCODE -eq 0) {
    Write-Host ""
    Write-Host "========================================" -ForegroundColor Green
    Write-Host "SUCCESS! Infrastructure configured." -ForegroundColor Green
    Write-Host "========================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Ready to deploy! Just run:" -ForegroundColor Cyan
    Write-Host "  git push origin master"
}
`;
    }
}
